### ISSUE TITLE
Variable length array declarations? (MSVC)

### ISSUE THREAD

**Issue by hu9o** [mmatyas/supermariowar#63]
Hi,
I tried again to build the project with Visual Studio, but I get multiple errors, one of them being:

In `FileIO.cpp` on lines [251][1] and [275][2], there are array declarations with a variable between the brackets (they definitely don't look like compile-time constants)... I thought it was impossible, can someone explain to me what's going on ?

Thanks

[1]: https://github.com/mmatyas/supermariowar/blob/master/src/common/FileIO.cpp#L251
[2]: https://github.com/mmatyas/supermariowar/blob/master/src/common/FileIO.cpp#L275

**Comment by mmatyas** [comment]
It seems MSVC doesn't support creating arrays like this... I've replaced them with vectors for now, and also fixed some other Visual Studio compile errors. It *might* work now, though I still have some linker errors, which may or may not occur to you too.

**Comment by hu9o** [comment]
I always thought this kind of declaration was forbidden in C++. I replaced them with `std::string`s, but, like you, I get linker errors.

I spent hours trying to figure it out, to no avail:
I get `LINK : fatal error LNK1104: cannot open file 'SDL_image.lib'`, even though I used *SDL**2**_image.lib*.
I never entered *SDL_image.lib* once in cmake, and it's not anywhere in my project options.
I have no clue where MSVC finds this name, so I can't change it.

Can you help me ?

**Comment by mmatyas** [comment]
I've just pushed some more MSVC patches, it should build and link correctly now. I've set up automated build testing on Appveyor too, but only for SDL1 at the moment.

`#pragma comment` can be used to add additional linker parameters to the generated object file. I guess it was easier for the original developers to add dependencies like this, but such tasks are now handled by the build system (CMake).

You won't need to recompile the dependencies; zlib works perfectly, only SDL1 had some problems due to certain internal changes between the Visual Studio version. I've added a workaround which *should* work, but I haven't done too much testing on Windows yet.

Building with SDL2 should work too, just set the `USE_SDL2_LIBS` CMake flag to `ON`. Note that only SMW itself has been converted to SDL2, the Level and World editor won't compile.

**Comment by hu9o** [comment]
I'm sorry, but even with your updates, I still get:
`Error LNK2019 unresolved external symbol compress referenced in function (...)`
I tried linking to `zlib\lib\zdll.lib` without success, then I downloaded _"zlib 1.2.3 for Windows 9x/NT (DLL and static version)"_ and tried linking to `zlib-1.2.3-lib\lib\zlib.lib`, to no avail.

I only tried with SDL2 and `USE_SDL2_LIBS` enabled, if that's of any consequence.

Maybe you could provide me with a copy of your Zlib .lib/.dll file(s) for Windows x64 ?

**Comment by mmatyas** [comment]
I'm using *"zlib compiled DLL, version 1.2.8"* from `zlib.net`, and it seems to be working on both x86 and x64. Also I've added the SDL2 build to Appveyor, so I can confirm that SDL2 works too on x86. I have some troubles linking the x64-specific libs of SDL1/2, but zlib itself seems to work correctly (proably SDL too if you use its x86 libs even on x64).

**Comment by mmatyas** [comment]
In case you want to try it, [here](https://ci.appveyor.com/project/mmatyas/supermariowar/build/1.0.370/job/7c3ncirjptivtmvn/artifacts) is the `smw.exe`  for x86 using SDL2.

**Comment by mmatyas** [comment]
Have you managed to build it?

**Comment by hu9o** [comment]
No I haven't, couldn't get it to work :/

**Comment by mmatyas** [comment]
Since the original issue, there have been quite some changes in the configuration and testing system; the build are tested with Visual Studio, with SDL1 and 2, so not sure if the issue is still valid. I'm closing this for now, but if it turns out to be still an issue, feel free to report it!
