### ISSUE TITLE
Netplay issues in alpha

### ISSUE THREAD

**Issue by mmatyas** [mmatyas/supermariowar#8]
This issue is for collecting netplay-related bugs discovered during the alpha testing.

**Comment by mmatyas** [comment]
HerbFargus commented 2 days ago:

Initial Netplay Issues:

- Music isn't Synced (not sure if it should be or not)
- Pause doesn't work (the windows shows up but nothing pauses (also the pause text is offset too far to the left)
- Skins don't show up on the other player's build- it defaults to mario
- Can't use items/ the other player doesn't see them (like fire flowers)
- Gamepad controls don't save
- Fullscreen crashes on SDL2 build (when you press enter in the menu while you have fullscreen selected) Not sure if this is related to the retropie build specifically though.
- Sometimes you float through blocks
- Sometimes one character freezes in place
- When the game finishes and one player exits it just keeps going... it should exit for both.
- no netplay bot support yet

**Comment by mmatyas** [comment]
Ronoh55 commented a day ago

One more issue possibly related to floating through blocks.

Sometimes when a player breaks a block the graphic for it remains on the other's screen, but it is inactive (i.e. You can jump/fall straight through it). Sometimes going through that block causes a small lag or "float" through the box.

**Comment by mmatyas** [comment]
*mmatyas commented a day ago:*

Yeah, most of these are because it's still alpha. The following can be considered bugs though:

- Gamepad controls don't save: that's a bug, thanks!
- Fullscreen crashes on SDL2 build
- Sometimes one character freezes in place: could you tell more details?

**Comment by HerbFargus** [comment]
- When flying with a feather or pow hand if you get too high you die
- when you squish someone they don't visibly squish or respawn- it just keeps going though they do have the momentary invincibility that happens during respawn. It does make the squish sound though and does take away a life.

**Comment by mmatyas** [comment]
- When there is exactly one one block of space between the ground and a [?]-block, hitting it only activates it for the room's host.

**Comment by Dude00** [comment]
* if you join a room you're "locked" to that room, all attempts to join another room result in you joining that room, even if it's invalid
* if the player hosting joins through their external ip, they attempt to connect using some sort of lan ip. connecting through localhost is fine?
* rooms don't work with more than two players, seems to duplicate ips of player 2?
![mearpxe](https://cloud.githubusercontent.com/assets/6980127/9368272/8a8b9462-467f-11e5-8361-ef3e88523b23.png)

**Comment by Cyantext** [comment]
At 1:16 in this video (https://www.youtube.com/watch?v=9MFRJI_Gpuc) me and herbfargus were trying to start a game and I got a message saying "[Warning] An unexpected client is trying to join the game". From what I could gather nobody had seen that message before and I could never get it to show up again.

**Comment by mmatyas** [comment]
- Gamemode settings are selected randomly at the start, like when you start a quick game. This causes, for example, that players don't die when killed (they don't respawn, just lose health).

**Comment by Ronoh55** [comment]
Bugs associated with map previews, map/skin sharing.

1. Map previews don’t work for clients. They see the default 0smw map.
2. Skins aren’t always assigned to proper player. (ie. player 2 had player 3's chosen skin, and vice versa)
3. If player 1 is eliminated, player 2 assumes their skin.
4. Need to implement tileset sharing for more varied map sharing.

**Comment by mmatyas** [comment]
*Skins aren’t always assigned to proper player. (ie. player 2 had player 3's chosen skin, and vice versa)*

This should be fixed now, could you test it?

**Comment by Ronoh55** [comment]
Probably won't get a chance to until Wednesday, but I will test soon.

**Comment by mmatyas** [comment]
Should be fixed now:

- After you create a room once and exit out of it and try and enter the same room, it has an infinite joining.... notification. you have to reboot to get it to work
- if you join a room you're "locked" to that room, all attempts to join another room result in you joining that room, even if it's invalid
- Skins aren’t always assigned to proper player. (ie. player 2 had player 3's chosen skin, and vice versa)

**Comment by HerbFargus** [comment]
- SDL2 still Crashes/Freezes when in fullscreen on my Raspberry PI 2. It doesn't crash with SDL1.

**Comment by mmatyas** [comment]
- Connect dialog stucks right after adding a new entry

**Comment by HerbFargus** [comment]
whoever is set as host will have an input lag of 1-2 seconds
